import SwiftUI

// Generated by Supernova - do not modify manually
public struct AppMeasures {

    // Dimension
    public static let dimensionMeasureExample = 200 

    // Border Radius
    public static let borderRadiusRadius1 = 4 
    public static let borderRadiusRadius2 = 58 
    public static let borderRadiusRadius3 = 4 
}