import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {

    func border1Token() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 1) 
    }

    func borderNewName() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 4) 
    }
}