import SwiftUI

// Generated by Supernova - do not modify manually
public extension Text {

    func textStyleH1() -> some View {
        return self
            .font(Font.custom("Advent Pro-700", size: 57))
    }

    func textStyleH2() -> some View {
        return self
            .font(Font.custom("Advent Pro-700", size: 43))
    }

    func textStyleH3() -> some View {
        return self
            .font(Font.custom("Advent Pro-700", size: 32))
    }

    func textStyleH4() -> some View {
        return self
            .font(Font.custom("Advent Pro-700", size: 24))
    }

    func textStyleH5() -> some View {
        return self
            .font(Font.custom("Advent Pro-700", size: 21))
    }

    func textStyleLargeLead() -> some View {
        return self
            .font(Font.custom("Advent Pro-400", size: 24))
    }

    func textStyleMediumLead() -> some View {
        return self
            .font(Font.custom("Advent Pro-400", size: 21))
    }

    func textStyleButtonLabel() -> some View {
        return self
            .font(Font.custom("Advent Pro-400", size: 21))
            .textCase(.uppercase) 
    }

    func textStyleParagraph() -> some View {
        return self
            .font(Font.custom("Advent Pro-400", size: 18))
    }

    func textStyleSmallParagraph() -> some View {
        return self
            .font(Font.custom("Advent Pro-400", size: 16))
    }

    func textStyleTinyParagraph() -> some View {
        return self
            .font(Font.custom("Advent Pro-400", size: 12))
    }

    func textStyleSale() -> some View {
        return self
            .font(Font.custom("Advent Pro-700", size: 24))
            .textCase(.uppercase) 
    }

    /// typewriter font test
    func textStyleImpactLabel() -> some View {
        return self
            .font(Font.custom("Impact Label-400", size: 13))
    }

    /// importing test
    func textStylePoppins() -> some View {
        return self
            .font(Font.custom("Poppins-400", size: 13))
    }
}
