import SwiftUI

// Generated by Supernova - do not modify manually
public extension Gradient {
    
    static let Token = Gradient.TokenGradient()
    
    struct TokenGradient {

        public let 1Token = LinearGradient(
            gradient: Gradient(stops: [
                Gradient.Stop(color: Color(.sRGB, red: 64/255, green: 80/255, blue: 110/255, opacity: 0.19), location: 0),
                Gradient.Stop(color: Color(.sRGB, red: 34/255, green: 33/255, blue: 144/255, opacity: 1), location: 0.6870804398148148),
            ]),
            startPoint: UnitPoint(x: 0.5, y: 0),
            endPoint: UnitPoint(x: 0.5, y: 1) 
        )
    }
}