import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {

    func shadowShad1() -> some View {
        return self.shadow(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), radius: 0, x: 2, y: 2) 
    }
}